### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "2660918",
  "senha": "123456"
}


### BUSCAR USUÁRIO
GET http://localhost:3000/users/id/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiIyNjYwOTE4IiwiaWF0IjoxNzc2MjA4Mjc2LCJleHAiOjE3NzYyMDgzMzZ9.qFezTMeKUPQeVoTb8dyjiz0UTxj4n4ZwePOG3k5sI_U

