### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "2660918",
  "senha": "123456"
}


### BUSCAR USUÁRIO
GET http://localhost:3000/users/id/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiIyNjYwOTE4IiwiaWF0IjoxNzc2MjAwMDcyLCJleHAiOjE3NzYyMDAxMzJ9.1eKjlUXlYR0ntUZ2Sx_eU35kjGF1MYdjV-MHkbSNqBU

